create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nombre varchar not null
);

create table if not exists public.modelos (
  id bigint generated by default as identity primary key,
  nombre varchar not null,
  idMarca bigint not null references public.marcas(id) on delete restrict
);

create table if not exists public.coches (
  id bigint generated by default as identity primary key,
  color varchar not null,
  matricula varchar not null,
  idMarca bigint not null references public.marcas(id) on delete restrict,
  idModelo bigint not null references public.modelos(id) on delete restrict
);
